# SQL Server 2012 config
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=PERSONAL;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=daniel

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Puerto del servidor (opcional)
server.port=8086